package controlador;

import java.util.Collection;
import java.util.Date;
import java.util.Vector;

import modelo.Colocacion;
import modelo.PautaColocacion;
import modelo.Publicacion;
import modelo.Vendedor;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Sistema de Colocacion Publicaciones.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//

public class Sistema {
	private Vector<Vendedor> vendedores;
	private Vector<Publicacion> publicaciones;
	private Vector<PautaColocacion> pautasColocacion;
	private Vector<Colocacion> colocaciones;
	public void realizarColocacion(int codigoEdicion, Date fechaSalida) {
	
	}
	
	public void agregarEdicion() {
	
	}
	
	public void borrarEdicion(int codigoEdicion) {
	
	}
	
	public Vector<PautaColocacion> obtenerPautas() {
		return null;
	}
	
	public void activarPauta() {
	
	}
}
