package persistencia;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : MapperPublicacion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//

public class MapperPublicacion {
	public void getByCode() {

	}

	public void list() {

	}
}
