//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : MapperPauta.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class MapperPauta {
	public void insert() {
	
	}
	
	public void delete() {
	
	}
	
	public void update() {
	
	}
	
	public void getByCodigo() {
	
	}
	
	public void list() {
	
	}
}
