package persistencia;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;

import modelo.Edicion;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : MapperEdicion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class MapperEdicion {
	
	private static MapperEdicion instancia;
	
	public MapperEdicion() {
		
	}
	
	public static MapperEdicion getInstancia() {
		if (instancia == null)
			instancia = new MapperEdicion();
		return instancia;
	}
	
	public int insert(Object o) {
		try
		{
			Edicion a = (Edicion)o;
			Connection con = PoolConnection.getPoolConnection().getConnection();
			String script = "INSERT INTO A_Interactivas_01.dbo.Ediciones (TituloTapa, Precio, FechaSalida, Borrado) values (?,?,?,?) ";
			script += "SELECT scope_identity()";
			PreparedStatement s = con.prepareStatement(script);
			//agregar campos
			s.setString(1,a.getTituloTapa());
			s.setFloat(2, a.getPrecio());
			s.setDate(3, (Date) a.getFechaSalida());
			s.setBoolean(4, a.isBorrado());
			ResultSet result = s.executeQuery();
			PoolConnection.getPoolConnection().realeaseConnection(con);
			result.next();
			return result.getInt(1);
		}
		catch (Exception e)
		{
			System.out.println();
		}
		return -1;		
	}
	
	public void delete() {
	
	}
	
	public void update() {
	
	}
	
	public void getByCodigo() {
	
	}
	
	public void list() {
	
	}
}
