//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : MapperVendedor.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class MapperVendedor {
	public void select() {
	
	}
}
