package modelo;

import java.util.Date;
import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Colocacion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class Colocacion {
	private static int codigoColocacion;
	private Vector<ItemColocacion> items;
	private Date fecha;
}
