package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Diario.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class Diario extends Publicacion {
	public void getUltimasTresEdiciones() {
	
	}
}
