//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Edicion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class Edicion {
	private static int codigoEdicion;
	private String tituloTapa;
	private float precio;
	private Date fechaSalida;
	private boolean borrado;
}
