//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : ItemColocacion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class ItemColocacion {
	private int colocados;
	private int devueltos;
	private Edicion edicion;
	private Publicacion publicacion;
	private Vendedor vendedor;
}
