package modelo;

import java.util.Vector;

import vista.PautaView;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : PautaColocacion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public abstract class PautaColocacion {
	private boolean activa;
	private int codigo;
	public abstract int obtenerCarga(Vendedor ven, Vector<Colocacion> col);
	public PautaView obtenerVista() {
		return null;
	}
	public boolean estasActiva() {
		return this.activa;
	}
	public boolean sosLaPauta(int codigo){
		return this.codigo==codigo;
	}
	public void setActiva(boolean activa) {
		this.activa = activa;
	}
	
}
