//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : PautaAgotados.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class PautaAgotados extends PautaColocacion {
	private int cantUltimasEdiciones;
	public int obtenerCarga(Object Vendedor ven, Object Collection<Colocacion> col) {
	
	}
	
	public pautaView obtenerVista() {
	
	}
	
	public int obtenerCarga(Object Vendedor ven, Object Collection<Colocacion> col) {
	
	}
	
	public pautaView obtenerVista(Object String desc) {
	
	}
}
