//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : PautaColocacion.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public abstract class PautaColocacion {
	private boolean activa;
	private int codigo;
	public abstract int obtenerCarga(Object Vendedor ven, Object Collection<Colocacion> col);
	public abstract pautaView obtenerVista(Object String desc);
	public boolean estasActiva() {
	
	}
}
