package modelo;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Revista.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//

public class Revista extends Publicacion {

	public void getUltimasTresEdiciones() {

	}
}
