//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sistema de Colocación de Publicaciones
//  @ File Name : Vendedor.java
//  @ Date : 26/04/2015
//  @ Author : 
//
//




public class Vendedor {
	private int nroVendedor;
	private String direccion;
	private String zona;
	private int tipo;
}
